name: Tag

on:
  push:
    tags:
      # Tags are in semantic versioning format.
      - 'Xv*.*.*'

permissions:
  id-token: write
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          ref: ${{ github.ref_name }}
#
      - name: Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
